fill:
  material: "gray stained glass pane"
  amount: 1
  name: " "

center:
  material: "compass"
  amount: 1
  name: "Lobby"

inventory:
  size: 27
  name: "Wybierz serwer"
  sound: "block chest open"