name: bpLobby
version: 0.7
author: botprzemek
website: https://www.github.com/botprzemek/bpLobby/
description: All-in-one lobby plugin (1.18.2)
main: pl.botprzemek.bpLobby.LobbyPlugin
api-version: 1.18
softdepend: [PlaceholderAPI, Oraxen]