name: bpLobby
version: '${project.version}'
main: pl.botprzemek.bpLobby
api-version: 1.18
authors: [ botprzemek ]
description: botprzemek's Lobby plugin
website: www.botprzemek.pl
commands:
  bplobby:
    description: Pozwala graczowi na zarządzanie Lobby
    permission: bpLobby.bplobby
    permission-message: Nie masz permisji!
    aliases: [bpl]
  fly:
    description: Pozwala graczowi na latanie
    permission: bpLobby.fly
    permission-message: Nie masz permisji!
    aliases: [f, latanie]
  speed:
    description: Pozwala graczowi na szybsze poruszanie się
    permission: bpLobby.speed
    permission-message: Nie masz permisji!
    aliases: [s, predkosc]
  teleport:
    description: Pozwala graczowi na szybsze poruszanie się
    permission: bpLobby.teleport
    permission-message: Nie masz permisji!
    aliases: [ tp, przenies ]

