name: bpLobby
version: '${project.version}'
main: pl.botprzemek.bpLobby
api-version: 1.18
authors: [ botprzemek ]
description: botprzemek's Lobby plugin
website: www.botprzemek.pl
commands:
  fly:
    description: Pozwala graczowi na latanie
    permission: bpLobby.latanie
    permission-message: Nie masz permisji!
    aliases: [f, latanie]
  bplobby:
    aliases: [bpl]

