name: bpLobby
version: '${project.version}'
main: pl.botprzemek.bpLobby
api-version: 1.18
authors: [ botprzemek ]
description: botprzemek's Lobby plugin
website: www.botprzemek.pl
commands:
  bplobby:
    description: Pozwala graczowi na zarządzanie Lobby
    permission: bplobby.bplobby
    permission-message: Nie masz permisji!
    aliases: [bpl]
  fly:
    description: Pozwala graczowi na latanie
    permission: bplobby.fly
    permission-message: Nie masz permisji!
    aliases: [f, latanie]
  speed:
    description: Pozwala graczowi na szybsze poruszanie się
    permission: bplobby.speed
    permission-message: Nie masz permisji!
    aliases: [s, predkosc]
  teleport:
    description: Pozwala graczowi na szybsze poruszanie się
    permission: bplobby.teleport
    permission-message: Nie masz permisji!
    aliases: [ tp, przenies ]
  lobby-br:
    description: Pozwala na wysyłanie wiadomości serwerowych
    permission: bplobby.broadcast
    permission-message: Nie masz permisji!
    aliases: [powiedz, wiadomosc]
  players:
    description: Pozwala na pokazywanie i ukrywanie graczy
    permission: bplobby.hide-see
    permission-message: Nie masz permisji!
    aliases: [gracze, widok]
#  lobby:
#    description: Pozwala graczowi na wybór serwera przez gui bądź komendę
#    aliases: [ server, serwer, wybor ]
#  drops:
#    description: Pozwala graczowi na szybsze poruszanie się
#    permission: bpLobby.teleport
#    permission-message: Nie masz permisji!
#    aliases: [ drop, dropy, losowanie ]


